{
 "title": "Wio Greenhouse",
 "time": { "from": "now-14h", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "title": "Greenhouse", "type": "row", "gridPos": { "x": 0, "y": 0, "w": 24, "h": 1 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 1, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "wio_temperature{serial=\"c29e0bc7\"}",
     "legendFormat": "{{serial}}"
    },
    {
     "expr": "wio_temperature{serial=\"c29e0bc7\"} offset 1d",
     "legendFormat": "{{serial}} yesterday"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 1, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "wio_humidity{serial=\"c29e0bc7\"}",
     "legendFormat": "{{serial}}"
    },
    {
     "expr": "wio_humidity{serial=\"c29e0bc7\"} offset 1d",
     "legendFormat": "{{serial}} yesterday"
    }
   ]
  },
  {
   "title": "Lux",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 1, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "wio_lux{serial=\"c29e0bc7\"}",
     "legendFormat": "{{serial}}"
    },
    {
     "expr": "wio_lux{serial=\"c29e0bc7\"} offset 1d",
     "legendFormat": "{{serial}} yesterday"
    }
   ]
  }
 ]
}